### ISSUE TITLE
Support for Holman BTX1 Tap Mounted Smart Valve?

### ISSUE THREAD

**Issue by mkhabc** [scottmckenzie/holman-linux-python#1]
It is possible to support the BTX1?
- bluetoothctl scan displays and allows connection to the BTX1
- holmanctl doesn't discover them
- Is it to do with lines 90-92 in holman.py?
    HOLMAN_SERVICE_UUID = '0a75f000-f9ad-467a-e564-3c19163ad543'
    STATE_CHARACTERISTIC_UUID = '0000f004-0000-1000-8000-00805f9b34fb'
    MANUAL_CHARACTERISTIC_UUID = '0000f006-0000-1000-8000-00805f9b34fb'

**Comment by scottmckenzie** [comment]
In theory, it shouldn't be too hard to support. I used an Android app called nRF Connect to determine the service uuid and characteristic uuids. Once you know the service uuid add it to the SERVICE_UUIDS list and see if it is discovered. 

If the characteristics uuids are different for your device then they would need to be stored in a dictionary with the service uuid add the key.

**Comment by hmoffatt** [comment]
gattctl tells me the following about the BTX1 (which is their model CO3011B):

[f7:52:49:38:b8:e0] Discovered, alias = H-CO3011B
[f7:52:49:38:b8:e0] Connected
[f7:52:49:38:b8:e0] Discovered, alias = H-CO3011B
[f7:52:49:38:b8:e0] Resolved services
[f7:52:49:38:b8:e0]  Service [00001801-0000-1000-8000-00805f9b34fb]
[f7:52:49:38:b8:e0]  Service [46a60001-ca26-425a-9bc6-d917829d2906]
[f7:52:49:38:b8:e0]    Characteristic [46a60001-ca26-425a-9bc6-d917829d2906]
[f7:52:49:38:b8:e0]  Service [c521f000-0d70-4d4f-8e43-40d84c50ab38]
[f7:52:49:38:b8:e0]    Characteristic [0000f004-0000-1000-8000-00805f9b34fb]
[f7:52:49:38:b8:e0]    Characteristic [0000f003-0000-1000-8000-00805f9b34fb]
[f7:52:49:38:b8:e0]    Characteristic [0000e001-0000-1000-8000-00805f9b34fb]
[f7:52:49:38:b8:e0]    Characteristic [0000c002-0000-1000-8000-00805f9b34fb]
[f7:52:49:38:b8:e0]    Characteristic [0000c001-0000-1000-8000-00805f9b34fb]
[f7:52:49:38:b8:e0]    Characteristic [0000f005-0000-1000-8000-00805f9b34fb]
[f7:52:49:38:b8:e0]    Characteristic [0000f006-0000-1000-8000-00805f9b34fb]

The characteristic IDs for status and manual match, just the service ID is different.

I changed it here and I could switch on the timer manually successfully.

**Comment by scottmckenzie** [comment]
Support added by @hmoffatt in #2
